### PR TITLE
fixes issue #102, display correct num of projects

### PR DESCRIPTION
**Pull request by rkaufman13**
me again :) This should fix issue #102 following @k3KAW8Pnf7mkmdSMPHz27 's very helpful instructions!

### CODE REVIEW

**Comment by rkaufman13** [comment]
Ok, I swear I'm not trying to push broken code here. I see the deploy preview failed to compile; this fix works perfectly on my local machine. Let me know how I can help debug (or not, I'm afraid I'm a bit out of my depth here).

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
hi, sorry, haven't had time to review yet. I'll have time in the afternoon, just quickly I'd guess you don't see errors locally because,

1. You are behind the main branch? You might have to merge it into your branch
2. I have missconfigured something 😛  Which development environment are you using?

To fix the errors you'll probably have to pass the update state as its own parameter so that typescripts type inference works a bit better

**Review by k3KAW8Pnf7mkmdSMPHz27 — CHANGES_REQUESTED** [review]
First of all, thank you for looking at the issue in the first place, and I am happy if the instructions were useful! This bug has been around for a while and has shown up in at least one of Gio's presentations 

I see that your branch is up-to-date so you should at least get 2 errors when you run it locally. Based on the tabs/spaces in `ProjectsTable.tsx` it doesn't seem like Prettier is running/loading as it should either. I don't think I can give you much advice without knowing what you are programming in (I am using WebStorm but I'd recommend Visual Studio Code). My first step when something like this doesn't work when I know it should is to delete the local node_modules folder and run `yarn install` again and hope that it works :/

> this fix works perfectly on my local machine

The code works, and if we turned of ESLint/those warnings the preview would be working as well. The reason those warnings are turned on is that even if the code works, we want to use static code analysis to detect as many _potential_ sources of errors as possible. Your code works as is, but if someone isn't careful when they make changes to `options` at a later point, it can fail without warning.

So, to sum it all up, the code solves the bug, it works, and I think you only need minor changes to make it pass ESLint :)

---

Nitpick = change if you agree with my suggestion, it is something that is in my opinion subjective and I will approve the PR even if you don't change that part.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
P.S. 1. The ESLint/Prettier configs aren't really finalized yet. Sorry about that. There are some more details about it in #83. The short version is that there are some 90-150 small problems that should be addressed before they work as expected.

P.S. 2. If you are running into issues with the ESLint/Prettier you can ask in the Code for America Slack as well. People are usually very helpful in #engineering/#enginnering-help channels. There is also, of course the #brigade-project-index channel and I am most likely reachable as `@Jonathan Asketorp` (and otherwise`@Jonatan Asketorp`).

**Comment by rkaufman13** [comment]
Appreciate the detailed help. You are absolutely correct; I have two machines that I work on and apparently haven't set up Settings Sync, so the version of VScode I was testing on didn't have Prettier *or* ESLint. Gonna fix this up and try again.

**Comment by rkaufman13** [comment]
Ok, second time's the charm, I think.
I double checked in the React discord and my idea that you can't pass usestate setters directly as props is something I invented out of thin air(!) so I have updated the code to be more direct. Also changed the variable names to be more descriptive (rowCounter vs counter) for future readability. Thanks much!

**Review by k3KAW8Pnf7mkmdSMPHz27 — APPROVED** [review]
It looks good!

Also forgot to mention before but thank you for using a separate branch!

> I double checked in the React discord

Thank you for double-checking it! I am still at the stage where I spend quite a bit of time Googling whether I am following "best practices", having someone else contributing to that part is good 😃

**Pull request merged**
