### PR TITLE
issue #94, rm extra loading.. when 0 projects

### PR DESCRIPTION
**Pull request by rkaufman13**
Hi from a newbie! Saw this issue and I think I was able to fix it. Basically, ProjectsTable was using rows.length as a conditional for rendering loading, rather than looking for a loading state. HTH

### CODE REVIEW

**Comment by rkaufman13** [comment]
Hiya, refactored to use useContext as suggested. I think it does fix the related issue on /brigades as well..?

**Review by k3KAW8Pnf7mkmdSMPHz27 — CHANGES_REQUESTED** [review]
This looks good! The behavior of the `Loading...` on `/projects` and `/brigades` is exactly as I'd expect both locally and in the preview!

I'd still suggest two more changes, if you agree, the PR should be good to go afterward,

1. Dealing with the `<LoadingIndicator>` (I'll open up a separate issue regarding it as soon as I have time, it should either be changed or completely removed in the future)
2. When `No projects` should be shown

**Comment by rkaufman13** [comment]
Done, thanks!

**Review by k3KAW8Pnf7mkmdSMPHz27 — APPROVED** [review]
Looks good, thank you for your contribution!

If your browser has caching turned off, you should be able to see your changes on https://projects.brigade.network/ in a couple of minutes

**Pull request merged**
