### PR TITLE
Ethan/8/sort tags

### PR DESCRIPTION
**Pull request by ethanstrominger**
This is on top of previous pull request which moved filters from column to filter screen.  I copied feedback from that [pull request](https://github.com/codeforamerica/brigade-project-index-statusboard/pull/347) into this one.  All suggestions have been implemented except for "Display All xxx Projects" - there are significant performance issues if you do this.

Additionally: 
- Added checkboxes to hide/display column.
- Adjusted column sizes so that organization, project, issues, and changed since columns were fixed width.  This gives more space to description and tags.
- Sorted tags by name rather than frequency - it was confusing for me and I think having tags with similar prefixes to be next to each other.

### CODE REVIEW

**Comment by ethanstrominger** [comment]
Below are feedback from the meeting of 6/15.

Add some space between the blue line and the first selects of the filter, as well as underneath the filter.
Change the font of "Overview" and the title (now in bright blue) to match the font of the page.
Change "Looking to volunteer for an open source Civic Tech Github (and non Github) application?" into
"Looking for an open source Civic Tech GitHub project?"
Now it is missing the number of projects retrieved, it is useful, I'd put it back.
Organization select doesn't have reset functionality. Also right now, typing show a matching list of organizations. This is different from how it was before that was a text type ahead filter.
Make all dropdowns visually more consistent (make an issue).
Add space on left of the table header like it is on the right side.
We agreed on open the project page (when user click on the project name) in a new tab.
And to add another button at the bottom to say "Display All [x] Projects".

**Comment by giosce** [comment]
Great work @ethanstrominger!
Here are my initial comments (to keep in mind that preview seems to use larger font than real deployment):
- Font in the Filter section seems larger than the rest of the website
- "Search our curated list of Civic Tech Open Source applications for the ideal volunteer opportunity" I think we said to say "projects" instead of applications, in my opinion the list is not really "curated" and the purpose is not only for volunteer opportunities (we said it can be to see how many CfA projects tackle one issue, it can be to find projects for a client, etc.
- The "Hide/Show" button is graphically different
- I don't see the "Tags" selector anymore?
- I see that we open the project in a new tab. I think if you give it a name it will keep reusing the second opened tab, right now it keeps opening new tabs
- I'd leave the order of columns (project first) like it was before
- Hide/show columns is a great functionality. However, a) I don't think we need it with this number of columns, b) it takes too much space, those checkboxes are too prominent. I made the large "Only CfA" checkbox to match the other controls but I don't think they look nice these many.

**Comment by ethanstrominger** [comment]
@giosce Thanks for the review.  See comments to your review below.  Some I implemented others IMO were better to keep.  Reasoning is listed below.
- Font in the Filter section seems larger than the rest of the website
   - This is existing behavior.  Larger fonts for paragraphs read better?  If you go to About page
- "Search our curated list of Civic Tech Open Source applications for the ideal volunteer opportunity" I think we said to say "projects" instead of applications, in my opinion the list is not really "curated" and the purpose is not only for volunteer opportunities (we said it can be to see how many CfA projects tackle one issue, it can be to find projects for a client, etc.
  - I changed applications to projects.
  - I left the word "curated".  We do not show every project on Github so it is curated, even if minimally.
  - I changed the purpose part of the paragraph.  I did not remove volunteering but I added other reasons.  This is a good website for people interested in volunteering and so including the word "Volunteer" will help with google results.
- The "Hide/Show" button is graphically different
  - Fixed 
- I don't see the "Tags" selector anymore?
   - Can you be more specific
- I see that we open the project in a new tab. I think if you give it a name it will keep reusing the second opened tab, right now it keeps opening new tabs
  - Hmm.  IMO it is good to open in a new tab each time because (a) I might want to look at multiple projects and (b) I might reuse the tab for some other purpose so it would be annoying if the contents were changed  
- I'd leave the order of columns (project first) like it was before
Hide/show columns is a great functionality. However, a) I don't think we need it with this number of columns, b) it takes too much space, those checkboxes are too prominent. I made the large "Only CfA" checkbox to match the other controls but I don't think they look nice these many.
  - I left the options in but tried to improve the appearance by adding a divider and decreasing font size to be same as the table.  Depending on the width of your screen I have found it useful to hide columns and I think others would also.

**Comment by giosce** [comment]
Looking good!
Sorry, just some minor comment:
- I'd really use smaller, simpler checkbox for show/hide column. It is possible that I created the larger checkbox (for CfA only) as default checkbox, maybe you can just enforce a smaller size? Or we can try to change the class of the "CfA only" and leave the default checkbox for show/hide column (but I know isn't easy, checkbox customization is very limited).
- It seems that the label "Only Code For America?" is another (smaller) font
- Columns content can overlap. Try to filter for "Bike" in the Tags control
- "Last Push" over_a_year is wrapped up, it doesn't look good

**Comment by giosce** [comment]
There is still the overlapping of text columns and the breaking of over_a_year for last_push

https://deploy-preview-359--dreamy-snyder-8339ae.netlify.app/?timeRange=all%20time&topics=Bike

**Comment by giosce** [comment]
It looks good now!
If I can just leave 2 minor feedbacks (I'm picky sorry).
Wouldn't you put a 3 words explanation on the show/hide columns checkboxes? Like at the beginning of that line something like "show/hide columns" or similar?
If the project name (link) is long, it breaks/wraps ... off course. But even when removing columns, the description keep taking more and more width and the project name/link is almost the last one to gain width. Not sure if it is something addressable.

**Comment by ethanstrominger** [comment]
I added Show/Hide Columns.  The other issue would be hard to fix - the width of tag and description are variable, as these will often have a lot of text and the others are fixed.  If you hide both description and tags it expands.

**Pull request merged**
